'Neos.MarketPlace:Package':
  superTypes:
    'Neos.MarketPlace:Document': true
  ui:
    label: i18n
    icon: gift
    inspector:
      groups:
        metrics:
          label: i18n
        github:
          label: i18n
  childNodes:
    maintainers:
      position: 'start'
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          'Neos.MarketPlace:Maintainer': true
    versions:
      position: 'after maintainers'
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          'Neos.MarketPlace:Version': true
    readme:
      position: 'after versions'
      type: 'Neos.MarketPlace:Readme'
  properties:
    title:
      type: string
      ui:
        reloadIfChanged: true
        inspector:
          group: document
        label: i18n
    __title:
      search:
        indexing: '${q(node).property(''title'')}'
        elasticSearchMapping:
          type: text
          analyzer: ngrams
    description:
      type: string
      ui:
        reloadIfChanged: true
        inspector:
          group: document
        label: i18n
    lastSync:
      type: DateTime
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            format: 'd-m-Y H:i'
    time:
      type: DateTime
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            format: 'd-m-Y H:i'
    type:
      type: string
      ui:
        reloadIfChanged: true
        inspector:
          group: document
        label: i18n
    repository:
      type: string
      search:
        elasticSearchMapping:
          type: text
      ui:
        reloadIfChanged: true
        inspector:
          group: document
        label: i18n
    abandoned:
      type: string
      ui:
        reloadIfChanged: true
        inspector:
          group: document
        label: i18n
    lastActivity:
      type: DateTime
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            format: 'd-m-Y H:i'
      search:
        indexing: '${Date.format(q(node).property(''lastActivity''), "Y-m-d\TH:i:sP")}'
        elasticSearchMapping:
          type: date
          format: date_time_no_millis
    __neosCompatibility:
      search:
        indexing: '${MarketIndexing.extractCompatibility(q(node).children(''versions'').children(''[stability = true]'').get(), "neos/neos")}'
        elasticSearchMapping:
          type: version
    __flowCompatibility:
      search:
        indexing: '${MarketIndexing.extractCompatibility(q(node).children(''versions'').children(''[stability = true]'').get(), "neos/flow")}'
        elasticSearchMapping:
          type: version
    lastVersion:
      type: reference
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            nodeTypes:
              - 'Neos.MarketPlace:Version'
      search:
        indexing: '${MarketIndexing.prepareVersion(q(node).property(''lastVersion''))}'
        elasticSearchMapping:
          type: object
          properties:
            name:
              type: text
            description:
              type: text
            keywords:
              type: text
              fields:
                name:
                  type: text
                tag:
                  type: keyword
                suggestion:
                  type: completion
                  analyzer: simple
                  search_analyzer: simple
            homepage:
              type: text
            version:
              type: text
            versionNormalized:
              type: long
            stability:
              type: boolean
            stabilityLevel:
              type: keyword
            time:
              type: date
              format: date_time_no_millis
            timestamp:
              type: integer
    downloadTotal:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    downloadMonthly:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    downloadDaily:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    favers:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    githubStargazers:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    githubWatchers:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    githubForks:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    githubIssues:
      type: integer
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    githubAvatar:
      type: string
      ui:
        reloadIfChanged: true
        inspector:
          group: metrics
        label: i18n
    __readme:
      search:
        indexing: '${String.stripTags(q(node).find(''readme'').first().property(''readmeSource''))}'
        fulltextExtractor: '${Indexing.extractHtmlTags(q(node).find(''readme'').first().property(''readmeSource''))}'
    __maintainers:
      search:
        indexing: '${q(node).find(''maintainers'').first().property(''title'')}'
        fulltextExtractor: '${Indexing.extractHtmlTags(q(node).find(''maintainers'').first().property(''title''))}'
    __packageKey:
      search:
        indexing: '${q(node).property(''title'')}'
        elasticSearchMapping:
          type: text
          fields:
            name:
              type: text
            tag:
              type: keyword
            suggestion:
              type: completion
              analyzer: simple
              search_analyzer: simple
    __composerVendor:
      search:
        indexing: '${Array.first(String.split(q(node).property(''title''), ''/''))}'
        elasticSearchMapping:
          type: text
    __packageType:
      search:
        indexing: '${MarketIndexing.packageTypeMapping(q(node).property(''type''))}'
        elasticSearchMapping:
          type: keyword
