'Neos.MarketPlace:Package':
  superTypes:
    'Neos.MarketPlace:Document': true
  ui:
    label: i18n
    icon: gift
    inspector:
      groups:
        metrics:
          label: i18n
        github:
          label: i18n
  childNodes:
    versions:
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          'Neos.MarketPlace:Version': true
  properties:
    title:
      type: string
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
    __title:
      search:
        indexing: '${q(node).property(''title'')}'
        elasticSearchMapping:
          type: text
          analyzer: ngrams
    description:
      type: string
      ui:
        inspector:
          group: document
          editorOptions:
            readonly: true
        label: i18n
    time:
      type: DateTime
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            format: 'd-m-Y H:i'
            readonly: true
    type:
      type: string
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
    repository:
      type: string
      search:
        elasticSearchMapping:
          type: text
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
    abandoned:
      type: string
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
    lastActivity:
      type: DateTime
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
            format: 'd-m-Y H:i'
      search:
        indexing: '${Date.format(q(node).property(''lastActivity''), "Y-m-d\TH:i:sP")}'
        elasticSearchMapping:
          type: date
          format: date_time_no_millis
    __neosCompatibility:
      search:
        indexing: '${MarketIndexing.extractCompatibility(q(node).children(''versions'').children(''[stability = true]'').get(), "neos/neos")}'
        elasticSearchMapping:
          type: version
    __flowCompatibility:
      search:
        indexing: '${MarketIndexing.extractCompatibility(q(node).children(''versions'').children(''[stability = true]'').get(), "neos/flow")}'
        elasticSearchMapping:
          type: version
    lastVersion:
      type: reference
      ui:
        label: i18n
        inspector:
          group: document
          editorOptions:
            readonly: true
            nodeTypes:
              - 'Neos.MarketPlace:Version'
      search:
        indexing: '${MarketIndexing.prepareVersion(q(node).property(''lastVersion''))}'
        elasticSearchMapping:
          type: object
          properties:
            description:
              type: text
            keywords:
              type: text
              fields:
                name:
                  type: text
                tag:
                  type: keyword
                suggestion:
                  type: completion
                  analyzer: simple
                  search_analyzer: simple
            homepage:
              type: text
            version:
              type: text
            versionNormalized:
              type: long
            stability:
              type: boolean
            stabilityLevel:
              type: keyword
            time:
              type: date
              format: date_time_no_millis
            timestamp:
              type: integer
    downloadTotal:
      type: integer
      ui:
        label: i18n
        inspector:
          group: metrics
          editorOptions:
            readonly: true
    favers:
      type: integer
      ui:
        label: i18n
        inspector:
          group: metrics
          editorOptions:
            readonly: true
    maintainers:
      type: string
      ui:
        label: Maintainers
        inspector:
          group: github
          editorOptions:
            readonly: true
    __packageKey:
      search:
        indexing: '${q(node).property(''title'')}'
        elasticSearchMapping:
          type: text
          fields:
            name:
              type: text
            tag:
              type: keyword
            suggestion:
              type: completion
              analyzer: simple
              search_analyzer: simple
    __composerVendor:
      search:
        indexing: '${Array.first(String.split(q(node).property(''title''), ''/''))}'
        elasticSearchMapping:
          type: text
    __packageType:
      search:
        indexing: '${MarketIndexing.packageTypeMapping(q(node).property(''type''))}'
        elasticSearchMapping:
          type: keyword
