Flowpack:
  Neos:
    Matomo:
      host: 'analytics.neos.io'
      token_auth: '%env:MATOMO_TOKEN_AUTH%'
      idSite:
        neosio: 5
        neosconio: 6
        flowneosio: 7
      containerId:
        # if you want those enabled for dev debugging, 
        # pls add a key and add no-tracking cookie so that 
        # your requests dont add up to our live-views
        #neosio: ''
        #neosconio: ''
        #flowneosio: ''
