Flowpack:
  Neos:
    Matomo:
      host: 'analytics.neos.io'
      token_auth: '%env:MATOMO_TOKEN_AUTH%'
      idSite:
        neosio: 1
        neosconio: 6
        flowneosio: 7
      containerId:
        neosio: 'Br6HvcZW_dev_bf9b48993030f1d7c5d9433c'
        neosconio: 'K0y3wsmz_dev_65f6e0bc8236b654d6cc6f51'
        flowneosio: 'm77ygDjK_dev_f462a5eceee3b49c26481290'
