Neos:
  Neos:
    userInterface:
      editPreviewModes:
        xs:
          title: 'Mobile'
          isEditingMode: true
          isPreviewMode: false
          position: 'end'
          width: 368
          backgroundColor: '#222'
        sm:
          title: 'Small'
          isEditingMode: true
          isPreviewMode: false
          position: 'after xs'
          width: 768
          backgroundColor: '#222'
        md:
          title: 'Tablet'
          isEditingMode: true
          isPreviewMode: false
          position: 'after sm'
          width: 908
          backgroundColor: '#222'
