Neos:
  Media:
    autoCreateThumbnailPresets: false
    image:
      defaultOptions:
        quality: 95
        webp_quality: 95
        jpeg_quality: 95
        png_compression_level: 1

    thumbnailPresets:
      # These should match prototype(MyVendor.AwesomeNeosProject:Component.PictureTag).srcSet
      'Neos.NeosIo:Thumbnails.200.jpg':
        width: 200px
        format: jpg
      'Neos.NeosIo:Thumbnails.200.webp':
        width: 200px
        format: webp
      'Neos.NeosIo:Thumbnails.400.jpg':
        width: 400px
        format: jpg
      'Neos.NeosIo:Thumbnails.400.webp':
        width: 400px
        format: webp
      'Neos.NeosIo:Thumbnails.600.jpg':
        width: 600px
        format: jpg
      'Neos.NeosIo:Thumbnails.600.webp':
        width: 600px
        format: webp
      'Neos.NeosIo:Thumbnails.800.jpg':
        width: 800px
        format: jpg
      'Neos.NeosIo:Thumbnails.800.webp':
        width: 800px
        format: webp
      'Neos.NeosIo:Thumbnails.1000.jpg':
        width: 1000px
        format: jpg
      'Neos.NeosIo:Thumbnails.1000.webp':
        width: 1000px
        format: webp
      'Neos.NeosIo:Thumbnails.1200.jpg':
        width: 1200px
        format: jpg
      'Neos.NeosIo:Thumbnails.1200.webp':
        width: 1200px
        format: webp
      'Neos.NeosIo:Thumbnails.1400.jpg':
        width: 1400px
        format: jpg
      'Neos.NeosIo:Thumbnails.1400.webp':
        width: 1400px
        format: webp
      'Neos.NeosIo:Thumbnails.1600.jpg':
        width: 1600px
        format: jpg
      'Neos.NeosIo:Thumbnails.1600.webp':
        width: 1600px
        format: webp

  Neos:
    modules:
      management:
        submodules:
          media:
            enabled: false
          mediaui:
            position: start
