Neos:
  Flow:
    http:
      applicationToken: 'MajorVersion'
    mvc:
      routes:
        'Neos.NeosIo': {}

    reflection:
      ignoredTags:
        # Hotfix for https://github.com/neos/flow-development-collection/issues/3585
        'type': true
