- name:  'ATOM Package Feed'
  uriPattern: '{node}.atom'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'atom'
  routeParts:
    'node':
      handler: 'Neos\Neos\FrontendRouting\FrontendNodeRoutePartHandlerInterface'
      options:
        uriPathSuffix: ''
        nodeType: 'Neos.MarketPlace:RepositoryStorage'

- name:  'Json Package API'
  uriPattern: '{node}.json'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'json'
  routeParts:
    'node':
      handler: 'Neos\Neos\FrontendRouting\FrontendNodeRoutePartHandlerInterface'
      options:
        uriPathSuffix: ''
        nodeType: 'Neos.MarketPlace:RepositoryStorage'
