Neos:
  Fusion:
    defaultContext:
      MarketPlaceSearch: Neos\MarketPlace\Eel\ElasticSearchQueryBuilder
      MarketPlace.Package: Neos\MarketPlace\Eel\PackageHelper
      MarketPlace.Input: Neos\MarketPlace\Eel\InputHelper
