#
# Settings used for development in Local Beach
#

Neos:
  Flow:
    persistence:
      backendOptions:
        host: '%env:BEACH_DATABASE_HOST%'
        dbname: '%env:BEACH_DATABASE_NAME%'
        user: '%env:BEACH_DATABASE_USERNAME%'
        password: '%env:BEACH_DATABASE_PASSWORD%'
        port: '%env:BEACH_DATABASE_PORT%'

    resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          targetOptions:
            relativeSymlinks: true

        localWebDirectoryPersistentResourcesTarget:
          targetOptions:
            relativeSymlinks: true

Flowpack:
  ElasticSearch:
    clients:
      default:
        - host: '%env:ELASTICSEARCH_HOSTNAME%'
          port: '%env:ELASTICSEARCH_PORT%'
          username: '%env:ELASTICSEARCH_USERNAME%'
          password: '%env:ELASTICSEARCH_PASSWORD%'
        - host: '%env:ELASTICSEARCH_HOSTNAME%'
          port: '%env:ELASTICSEARCH_PORT%'
          username: '%env:ELASTICSEARCH_USERNAME%'
          password: '%env:ELASTICSEARCH_PASSWORD%'

    indexes:
      default:
        'wwwneosio-development':
          analysis:
            filter:
              autocompleteFilter:
                max_shingle_size: 5
                min_shingle_size: 2
                type: 'shingle'
            analyzer:
              autocomplete:
                filter: [ 'lowercase', 'autocompleteFilter' ]
                char_filter: [ 'html_strip' ]
                type: 'custom'
                tokenizer: 'standard'

    ContentRepositoryAdaptor:
      driver:
        version: 2.x
